name: ci

on:
  push:
    branches:
      - dev

permissions:
  pull-requests: write

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Логинимся в кастомный docker-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Запускаем docker-команду
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          # Путь в котором будут выполняться комманды для сборки
          context: .
          file: ./Dockerfile
          push: true
          tags: docker-registry.toxiccat.ru/docker-static-website:latest

      # Автоматическое создание Pull Request'a из DEV ветки в MAIN
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "My pull request" --body "Description"
